### PR TITLE
refactoring thread-sensitive code out of Monitor

### PR DESCRIPTION
**Pull request by lookfwd**
Hello, how would you feel about refactoring the thread-sensitive code out of Monitor. It's just refactoring without any functional changes. This way we can add some focused steps around concurrency. I include one in this PR.

### CODE REVIEW

**Comment by romseygeek** [comment]
Hi Dimitrios, could you maybe explain a bit more what this will help with?  I'm not sure I see the benefit of adding another class to the API when this sort of thing really is internal to the working of the Monitor.

**Comment by scalingexcellence** [comment]
Slightly side-topic; `Indexable` being a top-level class is useful because it's used by the public top-level `QueryIndexUpdateListener`. Consequently I can see `QueryCacheEntry` soon becoming top-level because it's used by `Indexable`. But all those aren't really important.

I certainly agree that "adding another class to the API" is a bad thing and honestly I wouldn't like this to be another one on the top-level API. I believe that `WriterAndCache` shouldn't be part of the top-level API. It is though an complete layer on top of Lucene, irrelevant from the soon-to-become-God `Monitor` and it has all the concurrency complications that make it 100% worth being able to be tested independently.

After this refactoring Monitor has no synchronized methods and no Locks. It's easier by inspection to get a good feeling on if synchronization constraints are met or not within the `WriterAndCache` class. It's more difficult for someone to copy-paste less carefully and break the synchronization constraints adding race conditions etc. It's easier to inspect and understand if we have critical sections that span longer than the absolute minimum, thus decreasing concurrency. It's easy to assert and provide guarantees that e.g. the returned cache-entries won't be null for anything that exist on the index.

This is the main idea behind this refactoring. I can very well see how these 3 classes; `Indexable`, `QueryCacheEntry` and `WriterAndCache` might move to a package `uk.co.flax.luwak.cache` and form a nice little universe making `Monitor` cleaner business logic and making the entire framework more robust and well tested.

**Comment by lookfwd** [comment]
Slightly side-topic; `Indexable` being a top-level class is useful because it's used by the public top-level `QueryIndexUpdateListener`. Consequently I can see `QueryCacheEntry` soon becoming top-level because it's used by `Indexable`. But all those aren't really important.

I certainly agree that "adding another class to the API" is a bad thing and honestly I wouldn't like this to be another one on the top-level API. I believe that `WriterAndCache` shouldn't be part of the top-level API. It is though, a complete layer on top of Lucene, irrelevant to the soon-to-become-God `Monitor` and it has many concurrency complications that make it 100% worth being able to be tested independently.

After this refactoring `Monitor` has no synchronized methods and no `Locks`. It's easier by inspection to get a good feeling on if synchronization constraints are met within the more lean `WriterAndCache` class. It's more difficult for someone to copy-paste less carefully and break the synchronization constraints adding race conditions etc. It's easier to inspect and understand if we have critical sections that span longer than the absolute minimum, thus decreasing concurrency. It's easy to assert and provide guarantees that e.g. the returned cache-entries won't be null for anything that exists on the index.

This is the main idea behind this refactoring. I can very well see how these 3 classes; `Indexable`, `QueryCacheEntry` and `WriterAndCache` might live in a package `uk.co.flax.luwak.cache` and form a nice little universe leaving in `Monitor` more just business logic and making the entire framework more robust and well tested.

**Comment by romseygeek** [comment]
I'm convinced :-)

I've made a few changes here, renaming ```WriterAndCache``` to ```QueryIndex```, and then moving all the searcher manager related code into QueryIndex as well.  This has also allowed me to clean up the queryindex collection code, so many thanks for this!

**Comment by lookfwd** [comment]
Awesome! :)

**Pull request merged**
