### PR TITLE
Add a boolean storeMonitorQueries option to the Monitor

### PR DESCRIPTION
**Pull request by dcollins53**
Defaults to true (backwards compatible). If set to false, then the Monitor will not store the mq's as BinaryDocValues, thereby saving considerable amounts of memory.

The downside is that we can no longer get the original raw query out, but  I believe that is only for debug purposes anyway (or is there a functional use case that requires it)?

I need to add a test case for this still...

### CODE REVIEW

**Comment by romseygeek** [comment]
This looks good, thanks.  A test case would be good, though :-)

Rather than passing a boolean to the constructor, this probably belongs with things like configurePurgeFrequency() as a protected method.  At some point I'll get round to pulling all these configuration methods into a MonitorConfig object.

**Comment by romseygeek** [comment]
Another thing that occurs to me - if we're not storing the Monitor queries in the index, we'll need to ensure that if an IndexWriter is passed in to the monitor's constructor, it points at an empty index.  Otherwise the presearcher will be polluted by query terms that don't have any associated queries.

Maybe this is all best implemented as a Monitor subclass?  OneShotMonitor, or something with a better name than that...

**Comment by mjustice3** [comment]
Guess I don't get the point about the non-empty IndexWriter. Won't the clear() at line 115 be sufficient?

**Comment by romseygeek** [comment]
Yes, you're right - sorry, had missed that.

**Comment by romseygeek** [comment]
OK, I've pulled this in as https://github.com/flaxsearch/luwak/commit/d4391d66a0b8b4650f7e4fd63d0451bdbd6d6276 after a bit of refactoring.  Thanks!

**Comment by mjustice3** [comment]
Hmm, I still see an unconditional:

doc.add(new BinaryDocValuesField(FIELDS.mq, MonitorQuery.serialize(mq)));

in buildIndexableQuery().

**Comment by romseygeek** [comment]
Oops, yes.  Fixed by 79bfa9270bee742bc7c11e03e1b1dbea6072965a

**Pull request closed without merging**
