### PR TITLE
Loading 3x faster (for my use case)

### PR DESCRIPTION
**Pull request by lookfwd**
Hello,

Out of some load-time profiling we found the following optimizations that might give large improvements in load time. What do you think?

Cheers

### CODE REVIEW

**Comment by romseygeek** [comment]
This is to avoid re-indexing decomposed queries multiple times, right?  Looks good, I'll merge it in assuming it passes the travis tests.

**Comment by lookfwd** [comment]
Yes, It avoids re-indexing decomposed queries and completely avoids reading the query in case it has seen that subscription (id) before.

**Comment by lookfwd** [comment]
Hello, "fixed it" by triggering rebuild (no functional changes). Weird that Travis was somewhat unstable... or the tests? You might like to have a look on t he build failure above.

**Comment by romseygeek** [comment]
Looks like it was just a timing issue with the slowlog tests.  Thanks!

**Pull request merged**
