### PR TITLE
added metadata back to matchers

### PR DESCRIPTION
**Pull request by dyshi**
API change to the candidate matcher to pass metadata down.

### CODE REVIEW

**Comment by romseygeek** [comment]
Thanks, this looks good.

If we're going to be sharing metadata between different decomposed queries, and holding on to it after MonitorQuery objects have been added, I think we should make the map properly immutable, ie wrap it with Collections.unmodifiableMap(), and pass Collections.emptyMap() as the default.  

One style nit: could you put a space in ```Map<String, String>```

**Comment by dyshi** [comment]
yup will update in a bit thanks!

**Comment by romseygeek** [comment]
Plus it would be good to have a test for this, maybe just an anonymous Matcher subclass that asserts that it has the metadata passed to it?

**Comment by dyshi** [comment]
Oh yeah, definitely should've wrapped it there, will change. I'll also add the unit test.

**Comment by dyshi** [comment]
Hey @romseygeek I've moved the unmodifiableMap to the MonitorQuery class. For the constructor without metadata, I didn't want to double wrap a map, but I can change that to the emptyMap as well.

After adding the test case, I've also noticed that there is a sporadic test failure in TestParallelMatcher, for testMatchesAreDisambiguated, and consistent failure for testAllMatchesAreCollected with the following stacktrace.

Also observed this error in our internal system tests that uses Luwak 1.2.0 as well, and we suspect it is a race condition somewhere.
Thanks!
java.lang.RuntimeException: Interrupted during match
	at uk.co.flax.luwak.matchers.ParallelMatcher.finish(ParallelMatcher.java:114)
	at uk.co.flax.luwak.Monitor.match(Monitor.java:476)
	at uk.co.flax.luwak.Monitor.match(Monitor.java:457)
	at uk.co.flax.luwak.matchers.ConcurrentMatcherTestBase.testMatchesAreDisambiguated(ConcurrentMatcherTestBase.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:168)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.util.concurrent.ExecutionException: java.lang.AssertionError
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at uk.co.flax.luwak.matchers.ParallelMatcher.finish(ParallelMatcher.java:103)
	... 39 more
Caused by: java.lang.AssertionError
	at org.apache.lucene.util.BytesRefHash.compact(BytesRefHash.java:148)
	at org.apache.lucene.util.BytesRefHash.sort(BytesRefHash.java:164)
	at org.apache.lucene.index.memory.MemoryIndex$Info.sortTerms(MemoryIndex.java:723)
	at org.apache.lucene.index.memory.MemoryIndex$MemoryIndexReader$MemoryTermsEnum.<init>(MemoryIndex.java:906)
	at org.apache.lucene.index.memory.MemoryIndex$MemoryIndexReader$MemoryFields$1.iterator(MemoryIndex.java:842)
	at org.apache.lucene.index.TermContext.build(TermContext.java:93)
	at org.apache.lucene.search.TermQuery.createWeight(TermQuery.java:192)
	at org.apache.lucene.search.IndexSearcher.createWeight(IndexSearcher.java:855)
	at org.apache.lucene.search.IndexSearcher.createNormalizedWeight(IndexSearcher.java:838)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:486)
	at uk.co.flax.luwak.matchers.CollectingMatcher.doMatchQuery(CollectingMatcher.java:55)
	at uk.co.flax.luwak.CandidateMatcher.matchQuery(CandidateMatcher.java:63)
	at uk.co.flax.luwak.matchers.ParallelMatcher$MatcherWorker.call(ParallelMatcher.java:134)
	at uk.co.flax.luwak.matchers.ParallelMatcher$MatcherWorker.call(ParallelMatcher.java:119)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by romseygeek** [comment]
The stacktrace implies that something is calling functions on MemoryIndex before freeze() is called, which seems wrong.  Or possibly its a bug in MemoryIndex itself.  Could you raise a separate issue for that?

**Comment by dyshi** [comment]
changed the tests, and will add a separate issue thanks!

**Pull request merged**
