### PR TITLE
Implement commitWithin logic in Luwak

### PR DESCRIPTION
**Pull request by dcollins53**
This is analogous to commitWithin in Solr-speak, instead of having every query commit immediately, we allow a time-based batching to occur.  There is the batch insert/update interface, but that makes sense if the caller has specific batches of requests that come in.

We have single requests but they are very frequent, so to avoid IO contention on the index, we batch up the commit operation.  There is some lag on the queries being "active", but that can be configurable.

It defaults to the existing "commit every query" behavior.

### CODE REVIEW

**Comment by romseygeek** [comment]
Rather than having this as part of the Monitor code itself, I think it might make more sense to have a wrapper utility class (something along the lines of the ConcurrentQueryLoader that I added a few days ago)?

**Comment by romseygeek** [comment]
We talked about how to implement this at Revolution - @dcollins53 are you thinking about creating a separate pull request for a wrapper class?

**Comment by dcollins53** [comment]
Its on my list of things to do, I just haven't gotten around to it yet.

**Comment by romseygeek** [comment]
OK, no rush, I'm going to publish a 1.3.0 release early next week but this doesn't need to hold it up.

**Comment by dcollins53** [comment]
Going to withdraw this.  We are working on an alternative solution (as discussed at Revolution), but its not going to bear any resemblance to this, so I think its best to start afresh.

**Pull request closed without merging**
