### PR TITLE
debug monitor

### PR DESCRIPTION
**Pull request by dcollins53**
Done this as an extension to Monitor to make it easier to merge, but it could be merged into the main Monitor if you are ok with that?

### CODE REVIEW

**Comment by romseygeek** [comment]
This patch exposes a lot of the queryindex internals, and I'm not sure that I want to do that.  Could you explain a bit more why you found these extra functions useful?

**Comment by dcollins53** [comment]
The issue we've found is instances where Luwak doesn't match and we think it should have matched.  Since there is no logging within Luwak itself, it is hard to work out what happened.

We had a bug where things weren't getting put in the cache properly, so debugSubscription was useful since it let us see when we had a catch mismatch.  The cause was our BatchMonitor (or the old 4.8.1-based equivalent), not Luwak itself, but we thought it might be useful to allow the ability to get to the internals (obviously with all the usual caveats about knowing what you are doing if you do that, its clearly an advanced feature).

iterateAllQueries is used to allow us to dump subscriptions to disk (again to allow comparisons, later debugging)

indexChecksums maybe specific to us, we exposed it again purely for some debugging purposes.  We can keep this in-house, it was more about whether it might be useful to others...

**Comment by romseygeek** [comment]
iterateAllQueries looks like it could be done with getQueryIds() and getQuery()?  Although that would be slower, I guess - I can see a faster sugar method might be useful there.

For cache debugging, I'd be interested to see if https://github.com/flaxsearch/luwak/wiki/Debugging-Luwak could be extended to give extra information here.  Would the information on that page have been useful?

**Comment by dcollins53** [comment]
Abandoning this for now, we haven't used this functionality in the last year in our old version, so it is highly questionable whether this adds value.

**Pull request closed without merging**
