### PR TITLE
Resource closing in tests

### PR DESCRIPTION
**Pull request by dcollins53**
Eclipse warned about these, and trying to run some of the tests in windows did give failures (Unix lets you delete open files, but Windows doesn't).

I don't think there is anything particular controversial here, but feel free to disagree :)

### CODE REVIEW

**Comment by romseygeek** [comment]
Stylistic nit more than controversy, could you use try-with-resources?  That way things still get closed even if there are test failures.

**Comment by dcollins53** [comment]
Fair point, will have a go.

**Comment by dcollins53** [comment]
Finally managed to get eclipse using sensible settings, so I *think* this is good now...

**Comment by romseygeek** [comment]
Thanks!

**Pull request closed without merging**
