### PR TITLE
Ensure that all lucene core queries are handled by the TermFilteredPresearcher

### PR DESCRIPTION
**Pull request by romseygeek**

### CODE REVIEW

**Comment by romseygeek** [comment]
There are 71 query implementations in the luwak lucene classpath (from core, sandbox, queryparser and queries) that we don't handle at the moment.  Some of them are not handleable, which is fine - we can explicitly exclude them.  Some will require quite a lot of work (eg PointInSetQuery, which can probably be dealt with via bounding-boxes in future) - we can mark these as a TODO.  Some are pretty low-hanging fruit.  Anybody who wants to pick up on the latter, feel free!

**Comment by mjustice3** [comment]
This looks good. Of the queries in the TODO list, I have an implementation of DisjunctionMaxQueryExtractor (standalone) which we use heavily. Actually you may have been the original author, but I'd be happy to convert it to the new way and contribute back if you'd like. Of the others, I currently only use PrefixQuery (very rarely) and MatchAllDocsQuery (is there anything to do for that one?).  

Tangentially related, I just noticed that you don't decompose the DisjunctionMaxQuery disjuncts in QueryDecomposer. But in our version (again I think you may be responsible but it was called FieldedDisjunctionMaxQuery then) the disjuncts are decomposed. Decomposing the disjuncts seems to work ok for us, is there any reason not to?

**Comment by romseygeek** [comment]
I guess MatchAllDocsQuery should always return an AnyNode, because that's literally what it's for... so that should move to the 'unhandled' list.  For the rest, PRs are always welcome!  The only reason I didn't do it as I went along is because I want to test things properly.

Decomposing DisjunctionMaxQuery also sounds like a good idea, could you open another issue for that?

**Comment by dcollins53** [comment]
This gives me a good chance to play with this.

We have a custom query we have added to our lucene build (in org.apache.lucene.search).  What is the "correct" way to add support for that?  I can create a custom TreeBuilder and manually add OurTreeBuilder.INSTANCE into the TreeBuilders.DEFAULT_BUILDERS.  But that means patching Luwak, which I would prefer not to do.

Is the preferred approach that we move our query so it isn't in Core Lucene, and then create a new PresearcherComponent which adds a builder for that query? Or is there a better suggestion?

**Comment by romseygeek** [comment]
> Is the preferred approach that we move our query so it isn't in Core Lucene, and then create a new PresearcherComponent which adds a builder for that query?

I think this is probably the way to go.  The presearcher component stuff is fairly underused at the moment, so feel free to smooth over any bumps you find!

**Pull request merged**
